import requests
from twilio.rest import Client
# Your API Key is generated by creating a free account with openweathermap
api_key = YOUR_API_KEY
parameters = {
#   Your Latitude and Longitude are used by the openweathermap API to determine the weather at your location
    "lat": YOUR LATITUDE,
    "lon": YOUR LONGITUDE,
    "appid": api_key,
    "exclude": "current,minutely,daily"}

response = requests.get(url="https://api.openweathermap.org/data/2.5/onecall", params=parameters)
response.raise_for_status()
# This returns the weather data as Json 
weather_data = response.json()
# This will return only the hourly weather data
weather_slice = weather_data["hourly"][:12]

# The Account Sid and Auth Token are generated from creating an account with Twilio
account_sid = YOUR ACCOUNT SID
auth_token = YOUR AUTH TOKEN

will_rain = False
for hour_data in weather_slice:
    if int(hour_data["weather"][0]["id"]) <700:
        will_rain = True
# If the variable will_rain is true the desired number will recieve an SMS with the message "It's going to rain today."  
if will_rain:
    client = Client(account_sid, auth_token)
    message = client.messages \
        .create(
        body="It's going to rain today. Remember to bring an ☔️",
        from_= PHONE NUMBER GENERATED BY TWILIO,
        to= YOUR PHONE NUMBER
    )
print(message.status)
